### ISSUE TITLE
Step by Step instructions for testing dummynet

### ISSUE THREAD

**Issue by SrujithPoondla** [luigirizzo/dummynet#9]
Does any one have tutorial for this because i didnt get any error while installation and configuring pipe.
But while sending traffic with iperf and testing with wireshark, it is not using the configured pipe bandwidth it is using directly the higher bandwidth which i am giving in iperf.

For example if i set my pipe for 3 Mbps bandwidth and use iperf to transfer data at 20 Mbps the result should be the transfer at 3 Mbps . But I am getting 20 Mbps transfer bandwidth when measuring with wireshark.

**Comment by spyhunter99** [comment]
what was the pipe configuration that you used?
